apiVersion: apps/v1
kind: Deployment
metadata:
  name: aminos-deployment
  labels:
    app: aminos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aminos
  template:
    metadata:
      labels:
        app: aminos
    spec:
      containers:
      - name: aminos
        image: shaungpatrick/amino:1.0.0
        ports:
        - containerPort: 3333
